### ISSUE TITLE
请问在项目中引用过来的时候 出现 contentEditable 相关错误怎么处理的呢？

### ISSUE THREAD

**Issue by safawo** [ElemeFE/vue-desktop#31]
ERROR in .vue-desktop/lib/form/upload.vue 
<input class="upload-result-clipboard" v-el:clipboard type="text" v-model="copyText" contentEditable>                                                                 
  Found camelCase attribute: contentEditable. HTML is case-insensitive. Use content-editable=undefined instead. Vue will automatically interpret it as
 camelCase in JavaScript.
 
![a](https://cloud.githubusercontent.com/assets/3942566/12709059/c4109f58-c8e2-11e5-8855-d2ef0385eca6.jpg)
![Uploading a.jpg…]()

**Comment by furybean** [comment]
最新版本已经解决，更新到 0.2.1 试试。
