### ISSUE TITLE
loading-mask 无法修改text

### ISSUE THREAD

**Issue by fu122zh** [ElemeFE/vue-desktop#40]
报错
Data field "text" is already defined as a prop. To provide default value for a prop, use the "default" prop option; if you want to pass prop values to an instantiation call, use the "propsData" option

修改vue-desktop/src/service/loading-mask.vue 82 行 props改为data可解决问题

**Comment by furybean** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@fu122zh 已更新，版本为 0.2.23。现在可以在打开 loading-mask 时传入 text：
```javascript
LoadingMask.open('请稍等');
```

**Comment by fu122zh** [comment]
thanks~
