### ISSUE TITLE
dialog点击右上角×和背景的关闭动作增加响应函数

### ISSUE THREAD

**Issue by starshiner** [ElemeFE/vue-desktop#43]
在使用vue-desktop的dialog时，关闭动作的触发目前包含点击背景，点击dialog右上角箭头，修改visible，当遇到如下需求时便会出现问题：
dialog中包含表单，当点击背景和dialog右上角箭头时，无法触发外部函数，从而表单内容会停留在关闭前的状态，下次点开dialog依然会显示之前关闭前的状态，无法满足PM的需求。
例如：
点开dialog初始状态
![2016-06-02 2 04 34](https://cloud.githubusercontent.com/assets/9931685/15735401/1fcb43d2-28cb-11e6-9936-fcf559c401d2.png)
修改了某一个
![2016-06-02 2 04 45](https://cloud.githubusercontent.com/assets/9931685/15735402/21383e3c-28cb-11e6-883d-539f536c8ae6.png)
此时点击背景，表单的状态会被维持且无法增加外部函数修改
![2016-06-02 2 04 45](https://cloud.githubusercontent.com/assets/9931685/15735402/21383e3c-28cb-11e6-883d-539f536c8ae6.png)

**Comment by Leopoldthecoder** [comment]
在使用 dialog 时，一般会将一个本地的变量双向绑定到 visible：
```html
<d-dialog :visible.sync="dialogVisible">
...
</d-dialog>
```
在 dialog 被关闭后，visible 变为 false，dialogVisible 变量也会变为 false。通过 watch 该变量，应该可以满足你的需求：
```javascript
watch: {
  dialogVisible(val) {
    if (!val) {
      // 将表单状态初始化
    }
  }
}
```
有问题再反馈～

**Comment by starshiner** [comment]
get 👍

**Comment by ppq1991** [comment]
mark
