### ISSUE TITLE
能不能搞个在线演示的

### ISSUE THREAD

**Issue by qq157788394** [ElemeFE/vue-desktop#45]

**Comment by bees** [comment]
I just put up a copy of the examples here: http://bees.github.io/vue-desktop-demo, but an official page would be awesome

**Comment by furybean** [comment]
感谢。这个项目实现的时候是没有 UED 参与的，对交互和视觉并不满意。我们在与 UED 合作重构这个项目，后面会有在线演示和文档。

**Comment by haochengxu** [comment]
thanks a lot

**Comment by qq157788394** [comment]
@furybean 你上回说的重构，啥时候能发啊？
