### ISSUE TITLE
Grid组件 hot reload时会出现错误

### ISSUE THREAD

**Issue by BITDM** [ElemeFE/vue-desktop#48]
第一次显示数据时正常，数据是使用vue-resource取回来的一个数组

修改组件时，会hot reload，接下来就会出现Grid的表头文字消失，同时在console下可以看到以下的错误：

> vue.common.js:1019 [Vue warn]: Error when evaluating expression ""grid_1_column_21 "+(columnsMap['grid_1_column_21'].direction)": TypeError: Cannot read property 'direction' of undefined

每一列都有类似的提示。

另外，定义Grid-column的时候，有某一列会出现在第3列，定义的位置是在后面。

**Comment by furybean** [comment]
第二个问题是 vue.js 本身的 bug：
https://github.com/vuejs/vue/pull/3149

第一个问题暂时无解。

**Comment by BITDM** [comment]
第一个问题现在修复了吗？还是只需要升级vuejs即可？

**Comment by furybean** [comment]
并没有，得等 vuejs 的 1.0.27。

**Comment by BITDM** [comment]
vuejs 1.0.26的commits里有一个是：https://github.com/vuejs/vue/commit/f8b9cce12db99f4177ac35c36ec7c6b9755a9dc3

是不是就是解决这个问题的？不过我试验了一下，无效，列还是会乱。

**Comment by furybean** [comment]
这个并没有发布在 1.0.26 的版本里。
