### ISSUE TITLE
富文本编辑器

### ISSUE THREAD

**Issue by qq157788394** [ElemeFE/vue-desktop#55]
既然这个定位后台，是不是可以集成进去一个富文本编辑器，后台用富文本编辑器的地方还是蛮多的。

另外，还有jquery的各种插件，在后台里面用的还是很频繁的，希望能给个方便的把这些引用进去的方法。

**Comment by furybean** [comment]
定位还是有点差距，并不是一个聚合，只是另一套解决方案。
富文本编辑器可以自己用 vue 封装个组件，还是挺容易的。
