### ISSUE TITLE
tooltip-content 不能传动态值吗？

### ISSUE THREAD

**Issue by jmy2123** [ElemeFE/vue-desktop#56]
<d-button v-tooltip tooltip-placement="right" tooltip-content="{{row.rejection}}">Right Tooltip</d-button>下的tooltip-content 可以接收到动态值  但是鼠标移动上去显示不出动态读取的值

**Comment by furybean** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@jmy2123 已修复，请升级 0.2.28
