### ISSUE TITLE
表格放置在tab中，初始化的宽度没办法自适应

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/vue-desktop#60]
表格组件放置在tab中展示，初始化的宽度没有自适应，如图：
![_20160722094725](https://cloud.githubusercontent.com/assets/10893176/17044299/70491b16-4ff1-11e6-8d6c-bfb79c962f09.png)

**Comment by furybean** [comment]
Fixed: use vue-desktop@0.2.30
