### ISSUE TITLE
Schema中嵌套对象在form表单中无法使用property.nestedProperty绑定

### ISSUE THREAD

**Issue by featherfly** [ElemeFE/vue-desktop#65]
像下面这样

`<d-form :model='post' :schema='postSchema'>
    <d-text-field property="privilege.startTime" :editor-width="140">
    </d-text-field>
</d-form>`

`var postSchema = new Schema({
    privilege: {
        type: 'object',
        default () {
            return {};
        },
        fields: {
            startTime: {
                label: '开始时间',
                type: 'datetime',
                required: true,
                rules: {
                    type: 'custom',
                    message: '输入不是一个有效时间',
                    validate() {
                        return this.privilegeStartTime instanceof Date;
                    }
                }
            }
        }
    }
}
`

**Comment by furybean** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@featherfly fixed in vue-desktop@0.2.31

**Comment by BITDM** [comment]
嵌套的对象可以绑定到表单中，但是对象中fields定义的mapping不起作用
